# Generated by Django 6.0.3 on 2026-03-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_addree_1_user_addree_2_user_addree_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_marketing_agree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_marketing_agree',
            field=models.BooleanField(default=False),
        ),
    ]
