# Generated by Django 6.0.3 on 2026-03-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_email_marketing_agree_user_sms_marketing_agree'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='bank_num',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
