# Generated by Django 6.0.3 on 2026-03-08 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(choices=[('deposit', '충전'), ('refund', '환불')], max_length=10)),
                ('amount', models.PositiveBigIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('confilmed_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '거절')], max_length=10)),
                ('memo', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
