# Generated by Django 6.0.3 on 2026-03-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet_list',
            name='confilmed_at',
        ),
        migrations.AddField(
            model_name='wallet_list',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallet_list',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
