# Generated by Django 6.0.3 on 2026-03-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_wallet_list_confilmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet_list',
            name='is_dupli',
            field=models.BooleanField(default=False),
        ),
    ]
